# /home/opme/opme/ext/nginx/conf/opme.conf

include     /opme/home/opme/opme/ext/nginx/conf/opme_proxy_params;

access_log  /opme/home/opme/opme/logs/nginx/access.log combined;
error_log   /opme/home/opme/opme/logs/nginx/error.log;

server {
    return 404;
}

server {
    listen       80;
    server_name  opme;
    root         /opme/home/opme/opme/apps/app; # deploy path
    index        index.html;

    # listen 에 ssl 키워드가 없어서, 아래 설정은 무시되는 것 같음.
    ssl_protocols              TLSv1.2 TLSv1.3;
    ssl_ciphers                ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers  on;

    location /favicon.ico {
        # deny all;
        root    /opme/home/opme/opme/apps;
        log_not_found off;
        access_log off;
    }

    # OPME docs(Document Page)
    location /opmedocs/ {
        root    /opme/home/opme/opme/apps;
    }

    location /static/ {
        root    /opme/home/opme/opme/apps/app;
    }

    location / {
        limit_except GET POST {
            deny all;
        }
        # include     /opme/home/opme/opme/ext/nginx/conf/opme_proxy_params;
        proxy_pass  http://127.0.0.1:5000; # backend url
    }

    # location / {
    #   try_files $uri $uri/ /index.html;
    # }
}
