# /home/opme/nginx/conf/opme.conf

access_log  /home/opme/logs/nginx/access.log;
error_log   /home/opme/logs/nginx/error.log;

server {
    return 404;
}

server {
    listen 8080 ;
    server_name opme;

    rewrite ^(.*) https://52.79.144.112:7443$1 permanent;
}

server {
    listen       7443 ssl default_server;
    server_name  opme;
    root         /home/opme/apps/app; # deploy path
    index        index.html;

    ssl_certificate      "/home/opme/nginx/ssl/server.pem";
    ssl_certificate_key  "/home/opme/nginx/ssl/server.key";

    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  1m;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    location /favicon.ico {
        # deny all;
        root    /home/opme/apps;
        log_not_found off;
        access_log off;
    }

    # OPME docs(Document Page)
    location /opmedocs/ {
        root    /home/opme/apps;
    }

    location /static/ {
        root    /home/opme/apps/app;
    }

    location / {
        include     /home/opme/nginx/conf/opme_proxy_params;
        proxy_pass  http://127.0.0.1:5000; # backend url
    }

    # location / {
    #   try_files $uri $uri/ /index.html;
    # }
}
