# /home/opme/opme/ext/nginx/conf/opme.conf

access_log  /opme_data/home/opme/opme_skpc/logs/nginx/access.log;
error_log   /opme_data/home/opme/opme_skpc/logs/nginx/error.log;


server {
    listen       5000 ssl default_server;
    server_name  opme;
    root         /opme_data/home/opme/opme_skpc/apps/app; # deploy path
    index        index.html;

    location /favicon.ico {
        # deny all;
        root    /opme_data/home/opme/opme_skpc/apps;
        log_not_found off;
        access_log off;
    }

    # OPME docs(Document Page)
    location /opmedocs/ {
        root    /opme_data/home/opme/opme_skpc/apps;
    }

    location /static/ {
        root    /opme_data/home/opme/opme_skpc/apps/app;
    }

    location / {
        include     /opme_data/home/opme/opme_skpc/ext/nginx/conf/opme_proxy_params;
        proxy_pass  http://127.0.0.1:5005; # backend url
    }

    # location / {
    #   try_files $uri $uri/ /index.html;
    # }
    error_page 497 https://10.90.80.205:8080$request_uri;
}
