/opme/home/opme/opme/logs/gunicorn/*.log
/opme/home/opme/opme/logs/nginx/*.log
/opme/home/opme/opme/logs/opme/*.log
{
    # daily, weekly, monthly 등 rotate 주기
    daily
    # 파일 보관 갯수
    rotate 180
    # 파일 보관 기간 180일
    maxage 180
    # 파일이 없어도 에러를 발생하지 않음
    missingok
    # 파일 크기가 0이면 rotate 를 하지 않음
    notifempty
    # 압축하지 않음
    nocompress
    # rotate 시에 날짜 형식으로 파일 확장자를 추가함
    dateext
    # date format 을 변경함
    dateformat .%Y%m%d
    # 어제날짜로 확장자를 붙임
    dateyesterday
    # 새로운 파일 생성시 권한
	create 640 opme opmate
	# 여러파일에 같은 rotate 를 적용
    sharedscripts
    # rotate 실행후에 실행될 script 정의
    postrotate
        # 이번달 str 을 생성 15일로 정의해야 전달정보 정의가 가능
        thismonth="$(date '+%Y/%m/15 00:00:00')"
        # gunicorn, nginx, opme 로그 디렉토리가 공통으로 위치할 경로 /opme/home/opme/opme/logs
        dir_path="/opme/home/opme/opme/logs"

        # gunicorn, nginx, opme 디렉토리 for문 시작
        for dir_log in ${dir_path}/gunicorn ${dir_path}/nginx ${dir_path}/opme
        do
            # 디렉토리가 없으면 pass
            if [ ! -d "${dir_log}" ]
            then
                continue;
            fi

            # 당월에서 6개월전까지 for 문 시작
            for i in {0..6}
            do
                # 전월 str을 조회
                month="$(date -d "$thismonth $i month ago" '+%Y%m')"
                # 해당월로 디렉토리 명을 정함
                dir_month="${dir_log}/${month}"
                # 해당월 디렉토리가 없으면 생성
                if [ ! -d "${dir_month}" ]
                then
                   mkdir "${dir_month}"
                fi
                # 해당월에 해당하는 로그 파일이 생성되어 있는지 조회 ex) 202311(월) -> 20231120 확장자 파일등
                find ${dir_log} -maxdepth 1 -type f -name "*log.${month}*" -exec mv {} ${dir_log}/${month} \;
            done

            # gunicorn, nginx, opme 디렉토리에서 180일이 지난 파일은 삭제
            find ${dir_log} -type f -name "*log*" -mtime +180 -exec rm -rf {} \;
            # gunicorn, nginx, opme 디렉토리로 이동
            cd ${dir_log};
            # gunicorn, nginx, opme 디렉토리에서 빈 디렉토리 삭제
            find . -empty -type d -delete;
        done

        # gunicorn (opme) 실행중 프로세스에 file reopen(로그) 시그널 전송
        if [ -f /opme/home/opme/opme/bin/opme.pid ]
		then
        	kill -USR1 `cat /opme/home/opme/opme/bin/opme.pid`
        fi
        # nginx 실행중 프로세스에 file reopen(로그) 시그널 전송
		if [ -f /opme/home/opme/opme/bin/nginx.pid ]
		then
        	kill -USR1 `cat /opme/home/opme/opme/bin/nginx.pid`
        fi
    endscript
}